name = "terryho618.github.io"
license = "MIT"
description = ""
homepage = "https://github.com/terryho618/terryho618.github.io"
tags = []
features = []
min_version = "0.1.0"

[author]
  name = "Terry Ho"
  homepage = "github.com/terryho618"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
